# Generated by Django 3.2.9 on 2021-11-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
