# Generated by Django 3.2.9 on 2021-11-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_app', '0002_rename_productos_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
